name: 中青自动阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0-12/4,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/bigchalizi/Youth_speed.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install
          npm install cron
          npm install request
      - name: '运行 【中青阅读】'
        run: |
          cd ~/js   
          node Youth_AutoRead.js
