name: 中青自动阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '0 */4 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/bigchalizi/Youth_speed.git ~/Youth_speed
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/Youth_speed
          npm install
          npm install cron
          npm install request
      - name: '运行 【中青阅读】'
        run: |
          cd ~/Youth_speed   
          node Youth_AutoRead.js
